### ISSUE TITLE
What the purpose of the web application and then the web application itself

### ISSUE THREAD

**Issue by 3osmic** [CbarNC/Group3-repo-projects#5]

**Comment by 3osmic** [comment]
We could have a restaurant management system. 

_Tasks that can be performed:_

1. Add items to menu
2. Make table reservations
3. Take customer orders
4. Print the menu
5. Print table reservations
6. Print customer orders

The only problem with this is that it might be too complex or include more work than we actually want to do.

**Comment by Talonness** [comment]
Recommend doing 1 and 4 but designing to adding 2..3..5..6

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Talonness** [comment]
May need one more but u will figure that out as you learn the tools

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 3osmic** [comment]
Should the web application include a login-in screen?

**Comment by Talonness** [comment]
Always a good thing and lots of examples but no

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
