### ISSUE TITLE
Ideas for future enhancements in project

### ISSUE THREAD

**Issue by 3osmic** [CbarNC/Group3-repo-projects#8]

**Comment by 3osmic** [comment]
Current Ideas for Future Enhancements:
1. Login Screen
2. Search bar to find food items
3. Have a heart next to the menu option for when they love something and want to access it faster
4. Give customers an option to save that same order in case they want to order it next time

**Comment by zigmr** [comment]
More ideas for future Enhancements:

1. Display details and pictures of the dish when the item is clicked.
2. Add to cart 
3. Review order and payment 
4. option to save payment method + delivery location
5. Estimate waiting time for pickup
